/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Enkarra (https://sketchfab.com/Enkarra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-halloween-cat-dba541e7635c49f190e2a32d9e67c6f9
Title: The Halloween cat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HalloweenCat(props) {
  const { nodes, materials } = useGLTF("/models/the_halloween_cat.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.eyes_LPSG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.initialShadingGroup}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/the_halloween_cat.glb");
