/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Witch(props) {
  const { nodes, materials } = useGLTF("/models/witch.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["Purple.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials["Black.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials["Yellow.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials["GreenLight.003"]}
        />
        <group position={[0.204, 0, -0.634]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={materials["GreenLight.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018_1.geometry}
            material={materials["Purple.008"]}
          />
        </group>
        <group position={[-0.204, 0, -0.634]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019.geometry}
            material={materials["Purple.008"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube019_1.geometry}
            material={materials["GreenLight.003"]}
          />
        </group>
        <group position={[0, 0, -0.704]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017.geometry}
            material={materials["Black.019"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials["GreenLight.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials["Green.003"]}
          />
          <group position={[0, -0.071, -0.768]} rotation={[-0.264, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube016.geometry}
              material={materials["Purple.008"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube016_1.geometry}
              material={materials["Black.019"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube016_2.geometry}
              material={materials["Yellow.010"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/witch.gltf");
